config/routes.rb
Sparedeck::Application.routes.draw do

  resources :template_decks do
    member do
      get 'rent', to:'template_decks#rent', as:'rent'
    end
  end

  # Authentication routes
  get 'signup/:invitation_token', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # Account routes
  get "account", to: "users#account", as: 'account'

  resources :users do
    resources :verification_quizzes, only:[:new, :create]
  end
  resources :sessions
  resources :password_resets
  resources :invitations

  # Static pages
  get 'terms-of-use', to: 'pages#terms', as:'terms'
  get 'contact-us', to: 'pages#contact', as:'contact'
  get 'frequently-asked-questions', to: 'pages#faq', as:'faq'
  get 'how-does-it-work', to: 'pages#about', as:'about'

  resources :card_sets
  resources :cards do
    member do
      get 'order', to:'order_cards#create_or_update', as:'order'
    end
    collection do
      get 'search'
    end
  end

  # Order routes
  get 'returned/:return_token', to:'orders#user_return', as:'user_return'
  get 'cart', to: 'orders#cart', as:'cart'
  get 'clear', to: 'orders#clear_cart', as:'clear_cart'
  resources :orders do
    member do
      patch 'process_schedule'
      get 'payment'
      get 'receipt'
      get 'cancel', action:'cancel', as: 'cancel'
      patch 'authorize_payment'
      post 'coupon_code', action:'coupon_code', as: 'coupon_code'
    end
    resources :order_cards
  end

  # Admin routes
  namespace :admin do
    get "form-elements/:container/:partial", to:'orders#form_partial'

    get 'dashboard', to: 'pages#dashboard', as:'dashboard'
    get 'manage-default-prices', to: 'site_settings#manage_prices', as:'manage_prices'
    resources :verification_quizzes, only:[:show]
    resources :card_sets, :site_settings
    resources :template_decks do
      resources :template_deck_cards
    end
    resources :coupons
    resources :orders do
      resources :order_notes
      resources :stripe_charges
      member do
        get 'receipt'
        get 'cancel', action:'cancel', as: 'cancel'
        get 'shipped_form', action:'shipped_form', as:'shipped_form'
        patch 'shipped', action:'shipped', as:'shipped'
        get 'returned', action:'returned', as:'returned'
      end
      collection do
        get 'status/:status', action:'index', as:'status'
      end
    end
    resources :stripe_charges do
      member do
        get 'refund', action:'refund', as:'refund'
      end
    end
    resources :cards do
      collection do
        get 'search'
      end
    end
    resources :users do
      member do
        get 'toggle_admin'
      end
    end
  end

  root 'pages#home'

end

app/views/admin/pages/dashboard.html.erb
<h1>Admin Dashboard</h1>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Card dashboard</h4>
      </div>
      <div class="list-group">
        <%= link_to "Manage Inventory", admin_card_sets_path, class:'list-group-item' %>
        <%= link_to 'Manage Default Prices', admin_manage_prices_path, class:'list-group-item' %>
        <%= link_to 'Template Decks', admin_template_decks_path, class:'list-group-item' %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Order dashboard</h4>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to 'Open orders', status_admin_orders_url(:open) %>
          <span class="badge"><%= Order.open.count %></span>
        </li>
        <li class="list-group-item">
          <%= link_to 'Closed orders', status_admin_orders_url(:closed) %>
          <span class="badge"><%= Order.closed.count %></span>
        </li>
        <li class="list-group-item">
          <%= link_to 'Canceled orders', status_admin_orders_url(:canceled) %>
          <span class="badge"><%= Order.canceled.count %></span>
        </li>
        <li class="list-group-item">
          <%= link_to 'Coupons', admin_coupons_url %>
          <span class="badge"><%= Coupon.active.count %></span>
        </li>
      </ul>
    </div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Users dashboard</h4>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <%= link_to 'Manage Users', admin_users_path %>
          <span class="badge"><%= User.non_guest.count %></span>
        </li>
      </ul>
    </div>
  </div>

</div>