config/routes.rb
Sparedeck::Application.routes.draw do

  resources :template_decks do
    member do
      get 'rent', to:'template_decks#rent', as:'rent'
    end
  end

  # Authentication routes
  get 'signup/:invitation_token', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # Account routes
  get "account", to: "users#account", as: 'account'

  resources :users do
    resources :verification_quizzes, only:[:new, :create]
  end
  resources :sessions
  resources :password_resets
  resources :invitations

  # Static pages
  get 'terms-of-use', to: 'pages#terms', as:'terms'
  get 'contact-us', to: 'pages#contact', as:'contact'
  get 'frequently-asked-questions', to: 'pages#faq', as:'faq'
  get 'how-does-it-work', to: 'pages#about', as:'about'

  resources :card_sets
  resources :cards do
    member do
      get 'order', to:'order_cards#create_or_update', as:'order'
    end
    collection do
      get 'search'
    end
  end

  # Order routes
  get 'returned/:return_token', to:'orders#user_return', as:'user_return'
  get 'cart', to: 'orders#cart', as:'cart'
  get 'clear', to: 'orders#clear_cart', as:'clear_cart'
  resources :orders do
    member do
      patch 'process_schedule'
      get 'payment'
      get 'receipt'
      get 'cancel', action:'cancel', as: 'cancel'
      patch 'authorize_payment'
      post 'coupon_code', action:'coupon_code', as: 'coupon_code'
    end
    resources :order_cards
  end

  # Admin routes
  namespace :admin do
    get "form-elements/:container/:partial", to:'orders#form_partial'

    get 'dashboard', to: 'pages#dashboard', as:'dashboard'
    get 'manage-default-prices', to: 'site_settings#manage_prices', as:'manage_prices'
    resources :verification_quizzes, only:[:show]
    resources :card_sets, :site_settings
    resources :template_decks do
      resources :template_deck_cards
    end
    resources :coupons
    resources :orders do
      resources :order_notes
      resources :stripe_charges
      member do
        get 'receipt'
        get 'cancel', action:'cancel', as: 'cancel'
        get 'shipped_form', action:'shipped_form', as:'shipped_form'
        patch 'shipped', action:'shipped', as:'shipped'
        get 'returned', action:'returned', as:'returned'
      end
      collection do
        get 'status/:status', action:'index', as:'status'
      end
    end
    resources :stripe_charges do
      member do
        get 'refund', action:'refund', as:'refund'
      end
    end
    resources :cards do
      collection do
        get 'search'
      end
    end
    resources :users do
      member do
        get 'toggle_admin'
      end
    end
  end

  root 'pages#home'

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_cards, -> { order(:id) }, dependent: :destroy
  has_many :stripe_charges
  has_many :order_notes
  has_many :cards, through: :order_cards

  belongs_to :user
  belongs_to :coupon

  before_create :store_current_indiana_sales_tax
  before_create :create_return_token

  validates :return_token, uniqueness: true

  default_scope { order('orders.created_at desc') }

  scope :open, -> { where("orders.authorized IS NOT NULL AND orders.returned IS NULL AND orders.canceled IS NULL") }

  scope :authorized_not_yet_shipped, -> { where("orders.authorized IS NOT NULL AND orders.shipped IS NULL AND orders.returned IS NULL AND orders.canceled IS NULL")
  }

  scope :closed, -> { where("orders.returned IS NOT NULL") }

  scope :canceled, -> { where("orders.canceled IS NOT NULL") }

  # These are decks that are shipped but not returned and it is the day they are due back.
  scope :due_back, -> { where("orders.shipped IS NOT NULL AND orders.returned IS NULL AND orders.canceled IS NULL").where("orders.date_due_back < (?)", Time.zone.now) }

  # Current sales tax applied to IN residents. Also stored on orders
  # The logic is that it is set on order create but only applied if IN
  SALES_TAX_IN = '0.07'

  SHIPPING = { 'First Class' => { 'price' => 850, 's' => 'USPS First Class Parcel (2 - 4 Days)'}, 'Priority Mail' => { 'price' => 2000, 's' => 'USPS Priority Mail Express (1 - 2 days)' }, 'Free shipping' => { 'price' => 0, 's' => 'Local Pickup'} }

  def self.sales_tax_to_s
    value = "%.1f" % (SALES_TAX_IN.to_f * 100)
    "#{value}%"
  end

  def sales_tax_to_s
    value = "%.1f" % (sales_tax_in.to_f * 100)
    "#{value}%"
  end

  def self.last_cart
    where("orders.authorized IS NULL").order("created_at DESC").first
  end

  def cancel_order(origin)
    update_columns(canceled:origin)
    order_notes.create!(subject: "#{origin} canceled order")
  end

  def canceled_by_admin?
    (canceled == 'Admin') ? true : false
  end

  def store_current_indiana_sales_tax
    self.sales_tax_in = SALES_TAX_IN.to_f
  end

  def set_order_number
    order_no = "#{created_at.strftime('%M%d%y')}-#{id}"
    update_columns(order_no:order_no)
  end

  def was_canceled?
    (canceled.is_a? String) ? true : false
  end

  def sales_tax_in_dollars
    value_in_dollars(get_sales_tax)
  end

  def shipping_method_to_s
    SHIPPING[shipping_method]['s']
  end

  def shipping_method_price_in_dollars
    value_in_dollars(SHIPPING[shipping_method]['price'])
  end

  def due_back?
    true if Time.zone.now > date_due
  end

  def set_date_due_back
    date_due = date_needed + (days_needed).try('days')
    update_columns(date_due:date_due)
  end

  def total_cards
    order_cards.sum(:quantity)
  end

  def subtotal
    order_cards.map do |c| c.card_total end.sum
  end

  def subtotal_in_dollars
    "%.2f" % (self.subtotal.to_f / 100)
  end

  def subtotal_sum_in_dollars
    "%.2f" % ((self.subtotal + (self.duration_cost || 0)).to_f / 100)
  end

  def deck_due_back_soon
  end

  def authorize_amount
    charge = Stripe::Charge.create(
      :amount => order_total,
      :currency => 'usd',
      :customer => user.stripe_customer_id,
      :description => "Authorizing card for SpareDeck order",
      :capture => false
    )

    if charge
      update_columns(authorized:Time.zone.now)
    end

    rescue Stripe::CardError => e
      errors.add :base, e.json_body[:error][:message]
      return false
  end

  # Pricing calculation for deliver
  # Pricing Calculation: 3 days = Original cart price.
  # Each day after 3 days up to 7 days = Cart price + $1 per day
  # Each day after 7 days up to 30 days = Cart price + $7 + $0.50 per day

  def duration_cost(days = days_needed)
    days = 0 if days.nil?
    if days == 3
      cost = 0
    elsif days > 3 && days <= 7
      cost = 100 * days
    elsif(days > 7)
      cost = 700 + (50 * days)
    end
  end

  def duration_cost_in_dollars(days = days_needed)
    cents = duration_cost(days)
    value_in_dollars(cents)
  end

  def get_sales_tax
    if province == 'IN' || pickup
      cost =
      subtotal +
      duration_cost(days_needed) +
      SHIPPING[shipping_method]['price']
      sales_tax = (cost * SALES_TAX_IN.to_f).round.to_i
    else
      0
    end
  end

  def order_total
    subtotal +
    duration_cost(days_needed) +
    SHIPPING[shipping_method]['price']  +
    get_sales_tax -
    coupon_discount
  end

  def coupon_discount
    c = coupon

    return 0 if c.blank?

    case c.coupon_type
    when 'percentage'
      ((duration_cost(days_needed).to_f + subtotal.to_f) * (c.coupon_value.to_f/100 )).round.to_i
    end
  end

  # The status method is for display to users. From their point of view
  # an order may be placed, shipped, due back, returned or canceled.
  def status
    if canceled.present?
      return 'canceled'
    elsif returned.present?
      return 'returned'
    elsif due_back?
      return 'due back'
    elsif shipped.present?
      return 'shipped'
    elsif authorized
      return 'placed'
    else
      return 'placed'
    end
  end

  def receipt_status
    if canceled.present?
      return 'canceled'
    elsif returned.present?
      return 'paid'
    elsif due_back?
      return 'paid'
    elsif shipped.present?
      return 'paid'
    elsif authorized
      return 'placed'
    else
      return 'placed'
    end
  end

  def order_total_in_dollars
    value_in_dollars(order_total)
  end

  def value_in_dollars(value)
    "%.2f" % (value.to_f / 100)
  end

  def release_cards
  end

  def check_availability
    order_cards.each do |order_card|
      card = order_card.card
      available = card.available_for(date_needed, date_due, order_card.quantity)
      order_card.update_columns(available:available)
    end
  end

  def cleanup_unused_carts

  end

  def has_unavailables?
    true if (order_cards.collect{ |o| o.available }.include? false)
  end

  def shipping_info_present?
    true if street_address_first_line.present? && city.present? && province.present?
  end

  def create_return_token
    begin
      self.return_token = SecureRandom.urlsafe_base64
    end while Order.exists?(return_token: self.return_token)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  include CardsHelper
  before_action :authorize_admin
  before_action :set_order, only: [:show, :shipped_form, :shipped, :charge, :edit, :update, :returned, :receipt]

  def index
    case params[:status]
    when 'open'
      @orders = Order.open
    when 'closed'
      @orders = Order.closed
    when 'canceled'
      @orders = Order.canceled
    end

    @orders = @orders.paginate(page:params[:page], per_page:50)

  end

  def show
    @order = Order.find(params[:id])
    @order_cards_hash = parse_reference_deck_by_type(@order.order_cards)
    @card_type_array = card_type_array
  end

  def edit
    respond_to do |format|
      format.js {}
    end
  end

  def update
    @order.update(order_params)
    respond_to do |format|
      format.js {}
    end
  end

  def shipped_form
    respond_to do |format|
      format.js {}
    end
  end

  def cancel
    @order = Order.find(params[:id])

    if @order.shipped.nil?
      @order.cancel_order('Admin')
    else
      flash[:error] = 'The order has already shipped and cannot be canceled.'
    end

    respond_to do |format|
      format.html { redirect_to admin_order_path(@order) }
    end
  end

  def shipped
    @order.update(order_params)
    OrdersMailer.shipped(@order).deliver
  end

  def returned
    @order.returned = Time.zone.now
    @order.save
    @order.release_cards
    OrdersMailer.returned(@order).deliver
  end

  def receipt
    respond_to do |format|

      format.pdf do
        pdf = OrderPdf.new(@order, view_context)
        send_data pdf.render, filename: "order_#{@order.order_no}", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def form_partial
    respond_to do |format|
      format.js {}
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:date_needed, :days_needed, :date_due, :comment, :shipping_method, :street_address_first_line, :street_address_second_line, :city, :province, :zipcode, :country, :ship_to_name, :paid, :pulled, :shipped, :returned, :shipping_message, :shipping_reference_no, :sales_tax, :order_delayed, :billing_street_address_first_line, :billing_street_address_second_line, :billing_city, :billing_province, :billing_ship_to_name, :billing_zipcode, :billing_country, :billing_phone, :phone)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CardsHelper

  def show
    @order = current_user.orders.find(params[:id])
    @order_cards_hash = parse_reference_deck_by_type(@order.order_cards)
  end

  def index
    @orders = current_user.orders.all
  end

  def cancel
    @order = current_user.orders.find(params[:id])

    if @order.shipped.nil?
      @order.cancel_order('User')
    else
      flash[:error] = 'Your order has already shipped and cannot be canceled. To proceed please contact an admin at help@sparedeck.com'
    end

    respond_to do |format|
      format.html { redirect_to account_url }
    end
  end

  def cart
    # Is there a custom time theyre checking the cards out for?
    @custom = ([nil, 3, 14, 30].include? @cart.days_needed) ? false : true
    @time_now = Time.zone.now
    @min_date = 2.business_days.from_now.in_time_zone('Eastern Time (US & Canada)')

    if @cart.date_needed.present? && (@cart.date_needed >= 2.business_days.from_now.in_time_zone('Eastern Time (US & Canada)'))
      @display_date = @cart.date_needed
    else
      @display_date = 3.business_days.from_now.in_time_zone('Eastern Time (US & Canada)')
    end

    @order_cards_hash = parse_reference_deck_by_type(@cart.order_cards.includes(:card))
  end

  def user_return
    @order = Order.find_by(return_token:params[:return_token])

    @order.update_columns(user_return_confirmation:Time.zone.now) if @order

    respond_to do |format|
      format.html {}
    end
  end

  def process_schedule
    @cart.update_attributes(order_params)
    @cart.save

    @cart.set_date_due_back
    @cart.check_availability

    respond_to do |format|
      format.html {
        if (@cart.has_unavailables?)
          redirect_to cart_url
        else

          if @cart.order_no.blank?
            @cart.set_order_number
          end

          redirect_to payment_order_path(@cart)
        end
      }
    end

    # If cards are available for that date, the order is committed - unauthorized, to prevent other users from checking out cards.
  end

  def payment
    @order = current_user.orders.find(params[:id])
    @order_cards_hash = parse_reference_deck_by_type(@order.order_cards)
    if current_user.guest
      @invitation = Invitation.new
    end
  end

  def authorize_payment
    @order = current_user.orders.find(params[:id])
    @order.update_attributes(order_params)
    current_user.update_customer(params[:stripe_card_token])
    @order.authorize_amount

    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.first
      redirect_to payment_order_path(@order)
    else
      OrdersMailer.order_received(@order).deliver
      OrdersMailer.new_order(@order).deliver
      flash[:success] = 'Order received. You will be notified by email when your card is charged and when your deck ships!'

      respond_to do |format|
        format.html {
          if current_user.primary_verification_quiz.present? || (current_user.has_role? :admin)
            redirect_to account_url
          else
            redirect_to new_user_verification_quiz_path(current_user)
          end
        }
      end
    end

  end

  def edit
  end

  def coupon_code
    @order = current_user.orders.find(params[:id])
    @coupon = Coupon.active.find_by(coupon_code:params[:coupon_code])
    if @coupon.present?
      @cart.coupon_id = @coupon.id
      @cart.save
    end

    respond_to do |format|
      format.js {}
    end
  end

  def receipt
    @order = current_user.orders.find(params[:id])
    respond_to do |format|

      format.pdf do
        pdf = OrderPdf.new(@order, view_context)
        send_data pdf.render, filename: "order_#{@order.order_no}", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def clear_cart
    @cart.order_cards.destroy_all
    respond_to do |format|
      format.html { redirect_to cart_url }
    end
  end

  private

    def order_params
      params.require(:order).permit(:date_needed, :shipped, :returned, :amount, :days_needed, :date_due, :comment, :shipping_method, :ship_to_name, :stripe_card_token, :street_address_first_line, :street_address_second_line, :city, :province, :zipcode, :country, :billing_street_address_first_line, :billing_street_address_second_line, :billing_city, :billing_province, :billing_ship_to_name, :billing_zipcode, :billing_country, :billing_phone, :phone)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

  def format_date(date, options = {})
    return '' if date.blank?
    ## If event was less than a week ago  then time ago
    ## If event was last year, include year
    if options[:time]
      date.strftime('%b %d %Y %l:%M%P')
    else
      date.strftime("%b #{date.day.ordinalize}#{' %Y' if options[:year]}")
    end
  end

  def min_date
    Time.zone.now + 3.days
  end

  def checkbox_icon_boolean value
    if value.blank?
      html = "<span class='text-bold text-danger fa fa-times'></span>"
    else
      html = "<span class='text-bold text-success fa fa-check'></span>"
    end
    html.html_safe
  end

end

app/views/admin/orders/_attr_datetime_select.html.erb
<%= datetime_select(:order, attribute.to_sym, :discard_hour => true, :discard_minute => true, :discard_second => true, class:'form-control') %>

app/views/admin/orders/_delayed_form.html.erb
<div id="modal-form" class="modal" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-primary">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">
          Order Delayed
        </h4>
      </div>
      <%= form_for([:admin, @order], html:{class:'form-horizontal'}, remote:true) do |f| %>

      <div class="modal-body">
        <div class="row"><div class="col-md-11">

        <div class="help-block">
          <p>Use this form if the user will be delayed in returning the order. Indicate the number of days by which it is expected to be delayed. If any subsequent orders will be affected by this you will be emailed shortly.</p>
        </div>
        <div class="form-group">
          <%= f.label :order_delayed, "Number of days delayed", class:"col-sm-5 control-label" %>
          <div class="col-sm-4">
            <%= f.number_field :order_delayed, class:'form-control' %>
          </div>
        </div>

      </div></div>
      </div><!-- .modal-body -->

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> <%= f.submit "Save", class:'btn btn-primary' %>
      </div><!-- /.modal-footer -->

      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/admin/orders/_order_cards.html.erb
<div class="row order-section-row">
  <div class="col-md-12">

    <div class="order-section">
      <h3>Deck</h3>

      <ul id="order-card-list" class="list-group siteList bordered">
      <% @order_cards_hash.each do |card_type_index, order_cards| %>
        <% order_cards.each do |order_card| %>
        <li>
          <span class="card-pull-check padding-0-10"><input type="checkbox"></input></span>
          <span class="card-quantity padding-0-10 text-muted text-bold"><%= order_card.quantity %>x</span>
          <span class="card-name padding-0-10 text-primary text-bold"><%= order_card.card.name %></span>
          <span class="card-set padding-0-10 text-muted">(<%= order_card.card.card_set.code %>)</span>
        </li>
        <% end %>
      <% end %>
      </ul>
    </div>

  </div>
</div>

app/views/admin/orders/_order_controls.html.erb
<div id="order-controls">
<div class="row order-controls-row">
  <div class="col-md-4">
    <% if order.paid %>
    <%= link_to 'order paid', '#', class:'btn btn-block btn-success btn-outline active', disabled:true, id:'new-order-charge-link', remote:true %>
    <% else %>
    <%= link_to 'charge for order', new_admin_order_stripe_charge_path(order, charge_for_order:true), class:'btn btn-block btn-success btn-outline', id:'new-order-charge-link', remote:true %>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if order.shipped.present? %>
    <%= link_to "shipped #{order.shipped.strftime('%b %e')}", '#', class:'btn btn-block btn-primary btn-outline active', disabled:true, id:'new-order-charge-link', remote:true %>
    <% else %>
    <%= link_to 'ship order', shipped_form_admin_order_path(order), class:'btn btn-block btn-primary btn-outline', remote:true %>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if order.returned.present? %>
    <%= link_to "received #{order.returned.strftime('%b %e')}", '#', class:'btn btn-block btn-default btn-outline active', disabled:true, id:'order-returned-link', remote:true %>
    <% else %>
    <!-- Single button -->
    <div class="btn-group">
      <button type="button" class="btn btn-block btn-default btn-outline dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Deck receipt <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to 'deck received', returned_admin_order_path(order), class:'text-primary textbold', remote:true %></li>
        <li><%= link_to 'return delayed', edit_admin_order_path(order, delayed:true), class:'text-danger textbold', remote:true %></li>
      </ul>
    </div>


    <% end %>
  </div>
</div>

<div id="order-charge-form-target"></div>

</div>

app/views/admin/orders/_order_info.html.erb
<div id="order-info" class="row order-section-row">
  <div class="col-md-12">

    <div class="order-section">
      <% if order_controls %>
      <div class="order-controls pull-right">
        <%= link_to 'edit order', edit_admin_order_path(order), remote:true, class:'btn btn-sm btn-default btn-outline' %>

        <% if order.was_canceled? %>
          <%= link_to "cancel order", '#', data:{ confirm: 'Are you sure you want to cancel this order?' }, class:'btn btn-sm btn-danger btn-outline disabled', disabled:true %>
        <% else %>
          <%= link_to "cancel order", cancel_admin_order_path(order), data:{ confirm: 'Are you sure you want to cancel this order?' }, class:'btn btn-sm btn-danger btn-outline' %>
        <% end %>
      </div>
      <% end %>

      <h3><%= link_to "Order ##{@order.order_no}", admin_order_path(@order) %></h3>
      <table class="table">
        <tbody class="no-thead">
          <tr>
            <td class="order-table-label">User</td>
            <% if order.user.present? %>
            <td><%= "#{order.user.full_name} | #{order.user.email}" %></td>
            <% else %>
            <td>
              <span class="text-danger text-bold">User was deleted</span>
            </td>
            <% end %>
          </tr>

          <tr>
            <td class="order-table-label">Verification</td>
            <% if order.user.present? %>
            <td>
              <% if order.user.primary_verification_quiz.present? %>
                <%= link_to order.user.verification_status, admin_verification_quiz_path(order.user.primary_verification_quiz) %>
              <% else %>
                <%= order.user.verification_status %>
              <% end %>
            </td>
            <% else %>
            <td>
              <span class="text-danger text-bold">User was deleted</span>
            </td>
            <% end %>

          </tr>

          <tr>
            <td class="order-table-label">Date placed</td>
            <td><%= format_date order.authorized, {time:true} %></td>
          </tr>
          <tr>
            <td class="order-table-label">Date needed</td>
            <td><%= format_date order.date_needed %></td>
          </tr>
          <tr>
            <td class="order-table-label">Days needed</td>
            <td><%= order.days_needed %></td>
          </tr>
          <tr>
            <td class="order-table-label">Due back</td>
            <td><%= format_date order.date_due %></td>
          </tr>
          <tr>
            <td class="order-table-label">Shipping method</td>
            <td><%= order.shipping_method %></td>
          </tr>
          <tr>
            <td class="order-table-label">Billing Info</td>
            <td>
              <address>
                <%= order.billing_ship_to_name %><br>
                <%= order.billing_phone %><br>
                <%= order.billing_street_address_first_line %><br>
                <%= "#{order.billing_street_address_second_line}<br>".html_safe if order.billing_street_address_second_line.present? %>
                <%= "#{order.billing_city}, #{order.billing_province} #{order.billing_zipcode}" %>
              </address>
            </td>
          </tr>
          <tr>
            <td class="order-table-label">Shipping Info</td>
            <td>
              <address>
                <%= order.ship_to_name %><br>
                <%= order.phone %><br>
                <%= order.street_address_first_line %><br>
                <%= "#{order.street_address_second_line}<br>".html_safe if order.street_address_second_line.present? %>
                <%= "#{order.city}, #{order.province} #{order.zipcode}" %>
              </address>
            </td>
          </tr>
          <% if order.order_delayed.present? && order.order_delayed > 0 %>
          <tr>
            <td class="order-table-label">Order delayed</td>
            <td><%= order.order_delayed %> days</td>
          </tr>
          <% end %>
          <% if order_controls %>
          <tr>
            <td class="order-table-label">Printable receipt</td>
            <td><%= link_to "<span class='fa fa-file-text-o'></span>".html_safe, receipt_admin_order_url(order, format: "pdf") %></td>
          </tr>
          <% end %>

        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/admin/orders/_order_notes.html.erb
<div id="order-notes" class="row order-section-row">
  <div class="col-md-12">
    <div class="order-section">
      <h3>Order notes</h3>

      <div class="order-notes">
      <% order.order_notes.each do |note| %>
      <div class="row order-note-row">
        <div class="col-md-12">
          <% if note.subject.present? %>
            <%= "<h4>#{note.subject}<span class='created-at'><span class='fa fa-clock-o'></span>#{format_date note.created_at, {time:true}}</span></h4>".html_safe %>
          <% else %>
            <%= "<h4 class='h4-icon-only'><span class='created-at'><span class='fa fa-clock-o'></span>#{format_date note.created_at, {time:true}}</span></h4>".html_safe %>
          <% end %>
          <%= simple_format note.body %>
        </div>
      </div>
      <% end %>
      </div>

      <% if order.order_notes.count == 0 %>
      <p class="text-info text-bold">No notes have been added to this order</p>
      <br>
      <% end %>

      <%= link_to '<span class="fa fa-edit"></span> log note'.html_safe, new_admin_order_order_note_path(order), id:'new-order-note-link', class:'btn btn-outline btn-default btn-wd', remote:true %>

      <div id="order-note-form-target"></div>

    </div>
  </div>
</div>

app/views/admin/orders/_order_stripe_charges.html.erb
<div id="order-stripe-charges" class="row order-section-row">
  <div class="col-md-12">
    <div class="order-section">
      <h3>Stripe charges</h3>

      <ul id="stripe-charges" class="list-group siteList bordered">
      <% order.stripe_charges.each do |stripe_charge| %>
        <li>
          <span class="width-20 charge-date text-muted">
            <%= format_date stripe_charge.charge_date, {time:false} %>
          </span>
          <span class="width-15 charge-date text-bold text-success">
            $<%= stripe_charge.amount_in_dollars %>
          </span>
          <span class="width-45 charge-date text-muted longtext padding-0-10">
            <%= stripe_charge.card_charged %> | <%= stripe_charge.charge_type %>
          </span>
          <span class="width-15 refund-btn">
            <% unless stripe_charge.total_refunded? %>
            <%= link_to 'refund'.html_safe, refund_admin_stripe_charge_path(stripe_charge), class:'btn-sm btn-primary btn-outline btn', remote:true, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </span>
          <% if stripe_charge.stripe_refunds.count > 0 %>
          <% stripe_charge.stripe_refunds.each do |stripe_refund| %>
          <br>
          <span class="width-60 charge-date text-primary">
            charge refunded, date: <%= format_date stripe_refund.created_at %>, amount: $<%= stripe_refund.amount_in_dollars %>
          </span>
          <% end %>
          <% end %>
        </li>
      <% end %>
      </ul>

      <% if order.stripe_charges.count == 0 %>
      <p class="text-bold text-info">This user has not been charged yet.</p>
      <br>
      <% end %>

        <%= link_to '<span class="fa fa-credit-card"></span> Create New Charge'.html_safe, new_admin_order_stripe_charge_path(order), id:'new-stripe-charge-link', class:'btn btn-sm btn-success btn-outline btn-wd', remote:true %>

        <div id="charge-card-form-target"></div>
    </div><!-- .order-section -->

  </div>
</div>

app/views/admin/orders/form_partial.js.erb
<% if params[:partial] == 'shipped' %>
$("div.<%= params[:container] %>").html("<%= escape_javascript(render partial:'admin/orders/attr_datetime_select', locals:{attribute:'shipped'}) %>");
<% elsif params[:partial] == 'returned' %>
$("div.<%= params[:container] %>").html("<%= escape_javascript(render partial:'admin/orders/attr_datetime_select', locals:{attribute:'returned'}) %>");
<% end %>

app/views/admin/orders/shipped_form.js.erb
$("#form-target").html("<%= escape_javascript(render 'admin/orders/shipped_form') %>");
$('#modal-form').modal('show');