config/routes.rb
Sparedeck::Application.routes.draw do

  resources :template_decks do
    member do
      get 'rent', to:'template_decks#rent', as:'rent'
    end
  end

  # Authentication routes
  get 'signup/:invitation_token', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # Account routes
  get "account", to: "users#account", as: 'account'

  resources :users do
    resources :verification_quizzes, only:[:new, :create]
  end
  resources :sessions
  resources :password_resets
  resources :invitations

  # Static pages
  get 'terms-of-use', to: 'pages#terms', as:'terms'
  get 'contact-us', to: 'pages#contact', as:'contact'
  get 'frequently-asked-questions', to: 'pages#faq', as:'faq'
  get 'how-does-it-work', to: 'pages#about', as:'about'

  resources :card_sets
  resources :cards do
    member do
      get 'order', to:'order_cards#create_or_update', as:'order'
    end
    collection do
      get 'search'
    end
  end

  # Order routes
  get 'returned/:return_token', to:'orders#user_return', as:'user_return'
  get 'cart', to: 'orders#cart', as:'cart'
  get 'clear', to: 'orders#clear_cart', as:'clear_cart'
  resources :orders do
    member do
      patch 'process_schedule'
      get 'payment'
      get 'receipt'
      get 'cancel', action:'cancel', as: 'cancel'
      patch 'authorize_payment'
      post 'coupon_code', action:'coupon_code', as: 'coupon_code'
    end
    resources :order_cards
  end

  # Admin routes
  namespace :admin do
    get "form-elements/:container/:partial", to:'orders#form_partial'

    get 'dashboard', to: 'pages#dashboard', as:'dashboard'
    get 'manage-default-prices', to: 'site_settings#manage_prices', as:'manage_prices'
    resources :verification_quizzes, only:[:show]
    resources :card_sets, :site_settings
    resources :template_decks do
      resources :template_deck_cards
    end
    resources :coupons
    resources :orders do
      resources :order_notes
      resources :stripe_charges
      member do
        get 'receipt'
        get 'cancel', action:'cancel', as: 'cancel'
        get 'shipped_form', action:'shipped_form', as:'shipped_form'
        patch 'shipped', action:'shipped', as:'shipped'
        get 'returned', action:'returned', as:'returned'
      end
      collection do
        get 'status/:status', action:'index', as:'status'
      end
    end
    resources :stripe_charges do
      member do
        get 'refund', action:'refund', as:'refund'
      end
    end
    resources :cards do
      collection do
        get 'search'
      end
    end
    resources :users do
      member do
        get 'toggle_admin'
      end
    end
  end

  root 'pages#home'

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base

  scope :active, -> { where("coupons.start_date < (?) AND coupons.end_date > (?)", Time.zone.now, Time.zone.now) }

end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < ApplicationController
  before_action :authorize_admin
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  def index
    @coupons = Coupon.all
  end

  def new
    @coupon = Coupon.new
    respond_to do |format|
      format.js { render 'admin/coupons/launch_form' }
    end
  end

  def edit
    respond_to do |format|
      format.js { render 'admin/coupons/launch_form' }
    end
  end

  def create
    @coupon = Coupon.new(coupon_params)
    @coupon.save
    @coupons = Coupon.all
    respond_to do |format|
      format.js { render 'admin/coupons/render_table' }
    end
  end

  def update
    @coupon.update(coupon_params)
    @coupons = Coupon.all
    respond_to do |format|
      format.js { render 'admin/coupons/render_table' }
    end
  end

  def destroy
    @coupon.destroy
    @coupons = Coupon.all
    respond_to do |format|
      format.js { render 'admin/coupons/render_table' }
    end
  end

  private
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    def coupon_params
      params.require(:coupon).permit(:coupon_code, :start_date, :end_date, :coupon_type, :coupon_value, :use_count, :notes)
    end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/admin/coupons/_coupon_table.html.erb
<table id="coupons" class="table">
  <thead>
    <tr>
      <th>Coupon code</th>
      <th>Active dates</th>
      <th>Coupon type</th>
      <th>Coupon value</th>
      <th>Use count</th>
      <th>Notes</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.coupon_code %></td>
        <td><%= format_date coupon.start_date %>
 - <%= format_date coupon.end_date %></td>
        <td><%= coupon.coupon_type %></td>
        <td><%= coupon.coupon_value %></td>
        <td><%= coupon.use_count %></td>
        <td><%= coupon.notes %></td>
        <td class="col-md-1"><%= link_to "<span class='fa fa-cog'></span> edit".html_safe, edit_admin_coupon_path(coupon), remote:true, class:'btn btn-default btn-sm btn-outline btn-block' %></td>
        <td class="col-md-1"><%= link_to "<span class='fa fa-times-circle'></span> destroy".html_safe, admin_coupon_path(coupon), method: :delete, data: { confirm: 'Are you sure?' }, remote:true, class:'btn btn-danger btn-sm btn-outline btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/coupons/_form.html.erb
<%= form_for([:admin, @coupon]) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% @coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coupon_code %><br>
    <%= f.text_field :coupon_code %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :coupon_type %><br>
    <%= f.text_field :coupon_type %>
  </div>
  <div class="field">
    <%= f.label :coupon_value %><br>
    <%= f.number_field :coupon_value %>
  </div>
  <div class="field">
    <%= f.label :use_count %><br>
    <%= f.number_field :use_count %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/coupons/_modal_form.html.erb
<div id="modal-form" class="modal" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-primary">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">
          New Coupon
        </h4>
      </div>
      <%= form_for([:admin, @coupon], html:{class:'form-horizontal'}, remote:true) do |f| %>

      <div class="modal-body">
        <div class="row"><div class="col-md-10 col-md-offset-1">

        <div class="form-group">
          <%= f.label :coupon_code, class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :coupon_code, class:'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :start_date, class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.datetime_select :start_date, :discard_hour => true, :discard_minute => true, :discard_second => true, class:'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :end_date, class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.datetime_select :end_date, :discard_hour => true, :discard_minute => true, :discard_second => true, class:'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :coupon_type, class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.select :coupon_type, options_for_select([['Percentage','percentage'],['Free shipping','free shipping'],['Dollar amount','dollar amount']]),{}, class:'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :coupon_value, class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.number_field :coupon_value, class:'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :notes, class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_area :notes, rows:4, class:'form-control' %>
          </div>
        </div>
      </div></div>
      </div><!-- .modal-body -->

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> <%= f.submit "Save", class:'btn btn-primary' %>
      </div><!-- /.modal-footer -->

      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/admin/coupons/edit.html.erb
<h1>Editing coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/admin/coupons/index.html.erb
<h1>SpareDeck coupons</h1>

<%= render partial:'admin/coupons/coupon_table', locals:{coupons:@coupons} %>
<br>

<%= link_to 'New Coupon', new_admin_coupon_path, remote:true, class:'btn btn-wd btn-outline btn-default' %>

app/views/admin/coupons/launch_form.js.erb
$("#form-target").html("<%= escape_javascript(render 'admin/coupons/modal_form') %>");
$('#modal-form').modal('show');

app/views/admin/coupons/render_table.js.erb
$("table#coupons").replaceWith("<%= escape_javascript(render partial:'admin/coupons/coupon_table', locals:{coupons:@coupons}) %>");

$('#modal-form').modal('hide');
$('#modal-form').on('hidden.bs.modal', function () {
    $('#modal-form').remove();
});

app/views/admin/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coupon code:</strong>
  <%= @coupon.coupon_code %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @coupon.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @coupon.end_date %>
</p>

<p>
  <strong>Coupon type:</strong>
  <%= @coupon.coupon_type %>
</p>

<p>
  <strong>Coupon value:</strong>
  <%= @coupon.coupon_value %>
</p>

<p>
  <strong>Use count:</strong>
  <%= @coupon.use_count %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @coupon.notes %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>