config/routes.rb
Sparedeck::Application.routes.draw do

  resources :template_decks do
    member do
      get 'rent', to:'template_decks#rent', as:'rent'
    end
  end

  # Authentication routes
  get 'signup/:invitation_token', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # Account routes
  get "account", to: "users#account", as: 'account'

  resources :users do
    resources :verification_quizzes, only:[:new, :create]
  end
  resources :sessions
  resources :password_resets
  resources :invitations

  # Static pages
  get 'terms-of-use', to: 'pages#terms', as:'terms'
  get 'contact-us', to: 'pages#contact', as:'contact'
  get 'frequently-asked-questions', to: 'pages#faq', as:'faq'
  get 'how-does-it-work', to: 'pages#about', as:'about'

  resources :card_sets
  resources :cards do
    member do
      get 'order', to:'order_cards#create_or_update', as:'order'
    end
    collection do
      get 'search'
    end
  end

  # Order routes
  get 'returned/:return_token', to:'orders#user_return', as:'user_return'
  get 'cart', to: 'orders#cart', as:'cart'
  get 'clear', to: 'orders#clear_cart', as:'clear_cart'
  resources :orders do
    member do
      patch 'process_schedule'
      get 'payment'
      get 'receipt'
      get 'cancel', action:'cancel', as: 'cancel'
      patch 'authorize_payment'
      post 'coupon_code', action:'coupon_code', as: 'coupon_code'
    end
    resources :order_cards
  end

  # Admin routes
  namespace :admin do
    get "form-elements/:container/:partial", to:'orders#form_partial'

    get 'dashboard', to: 'pages#dashboard', as:'dashboard'
    get 'manage-default-prices', to: 'site_settings#manage_prices', as:'manage_prices'
    resources :verification_quizzes, only:[:show]
    resources :card_sets, :site_settings
    resources :template_decks do
      resources :template_deck_cards
    end
    resources :coupons
    resources :orders do
      resources :order_notes
      resources :stripe_charges
      member do
        get 'receipt'
        get 'cancel', action:'cancel', as: 'cancel'
        get 'shipped_form', action:'shipped_form', as:'shipped_form'
        patch 'shipped', action:'shipped', as:'shipped'
        get 'returned', action:'returned', as:'returned'
      end
      collection do
        get 'status/:status', action:'index', as:'status'
      end
    end
    resources :stripe_charges do
      member do
        get 'refund', action:'refund', as:'refund'
      end
    end
    resources :cards do
      collection do
        get 'search'
      end
    end
    resources :users do
      member do
        get 'toggle_admin'
      end
    end
  end

  root 'pages#home'

end

app/models/template_deck.rb
class TemplateDeck < ActiveRecord::Base
  has_many :template_deck_cards, dependent: :destroy
  has_many :cards, through: :template_deck_cards

  before_validation :ensure_name_has_a_value

  def price
    total = 0
    template_deck_cards.each do |template_deck_card|
      card_price = template_deck_card.card.get_price.to_f
      total += card_price * template_deck_card.quantity
    end
    return ("%.2f" % total)
  end

  protected
    def ensure_name_has_a_value
      if name.blank?
        self.name = "template_deck-#{Time.now.to_i}"
      end
    end

end

app/controllers/admin/template_decks_controller.rb
class Admin::TemplateDecksController < ApplicationController
  include CardsHelper

  before_action :authorize_admin
  before_action :set_template_deck, only: [:show, :edit, :update, :destroy]

  def index
    @template_decks = TemplateDeck.all.paginate(page:params[:page], per_page:50)
  end

  def show
    @template_deck_card_hash = parse_reference_deck_by_type(@template_deck.template_deck_cards.deck)
  end

  def new
    @template_deck = TemplateDeck.new

    respond_to do |format|
      format.js { render 'admin/template_decks/launch_form' }
    end
  end

  def edit

    respond_to do |format|
      format.js { render 'admin/template_decks/launch_form' }
    end
  end

  def create
    @template_deck = TemplateDeck.new(template_deck_params)
    @template_deck.save

    respond_to do |format|
      format.html { redirect_to admin_template_deck_path(@template_deck), notice: 'Template deck was successfully created.' }
    end
  end

  def update
    @template_deck.update(template_deck_params)
    respond_to do |format|
      format.html { redirect_to admin_template_deck_path(@template_deck), notice: 'Template deck was successfully updated.' }
    end
  end

  def destroy
    @template_deck.destroy
    respond_to do |format|
      format.html { redirect_to admin_template_decks_url }
    end
  end

  private
    def set_template_deck
      @template_deck = TemplateDeck.find(params[:id])
    end

    def template_deck_params
      params.require(:template_deck).permit(:name, :description)
    end
end

app/controllers/template_decks_controller.rb
class TemplateDecksController < ApplicationController

  def index
    @template_decks = TemplateDeck.all
  end

  def show
    @template_deck = TemplateDeck.find(params[:id])
  end

  def rent
    @template_deck
  end


  def rent
    @template_deck = TemplateDeck.find(params[:id])
    @template_deck.template_deck_cards.each do |template_deck_card|

      card = template_deck_card.card
      if card.present?
        order_card = @cart.order_cards.find_by(card_id:card.id)
        if order_card.blank?
          order_card = @cart.order_cards.build(card_id:card.id, quantity:template_deck_card.quantity, current_price:card.raw_price)
        else
          theoretical_quantity = order_card.quantity + template_deck_card.quantity
          order_card.quantity = (theoretical_quantity > 4) ? 4 : theoretical_quantity
        end
        order_card.save
      end
    end

    respond_to do |format|
      flash[:success] = 'Standard deck added to cart'
      format.html { redirect_to cart_path }
    end
  end


end

app/helpers/template_decks_helper.rb
module TemplateDecksHelper



end

# Card.all.to_a.collect{|c| c.types }.uniq
# => [["Creature"], ["Instant"], ["Enchantment"], ["Artifact"], ["Sorcery"], ["Land"], ["Artifact", "Creature"], ["Planeswalker"], ["Enchantment", "Creature"], ["Summon"], ["Vanguard"], ["Tribal", "Enchantment"], ["Enchant", "Creature"], ["Scariest", "Creature", "You'll", "Ever", "See"], ["Enchant", "Player"], ["Interrupt"], nil, ["Tribal", "Instant"], ["Artifact", "Land"], ["Eaturecray"], ["Tribal", "Sorcery"], ["Land", "Creature"], ["Enchantment", "Artifact"], ["Tribal", "Artifact"], ["Plane"], ["Scheme"], ["Phenomenon"], ["Conspiracy"]]

app/views/admin/template_decks/_modal_form.html.erb
<div id="modal-form" class="modal" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-primary">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">
          New Template Deck
        </h4>
      </div>

      <%= form_for([:admin, @template_deck], html:{class:'form-horizontal'}) do |f| %>

      <div class="modal-body">
        <div class="form-group">
          <%= f.label :name, class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_field :name, class:'form-control' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :description, class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= f.text_area :description, rows:6, class:'form-control' %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> <%= f.submit "Save", class:'btn btn-primary' %>
      </div><!-- /.modal-footer -->

      <% end %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/admin/template_decks/_sideboard_table.html.erb
<table id="template-deck-table-sideboard" class="table card-list-table <%= 'hide' if sideboard_template_deck_cards.blank? %>">
  <thead>
    <tr>
      <th colspan="6">Sideboard</th>
    </tr>
    <tr>
      <th>Card</th>
      <th>Qty</th>
      <th>Type</th>
      <th>Rarity</th>
      <th>Price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% sideboard_template_deck_cards.each do |template_deck_card| %>
      <%= render partial:'admin/template_decks/template_deck_tr', locals:{template_deck_card:template_deck_card} %>
    <% end %>
  </tbody>
</table>

app/views/admin/template_decks/_template_deck_table.html.erb
<table id="template-deck-table" class="table card-list-table <%= 'hide' if template_deck_card_hash.blank? %>">
  <thead>
      <th>Card</th>
      <th>Qty</th>
      <th>Type</th>
      <th>Rarity</th>
      <th>Price</th>
      <th></th>
  </thead>
  <tbody>
    <% template_deck_card_hash.each do |card_type, template_deck_cards| %>
      <tr class="card-table-title-row info">
        <td colspan="6"><%= card_type_array[card_type] %></td>
      </tr>
      <% template_deck_cards.each do |template_deck_card| %>
        <%= render partial:'admin/template_decks/template_deck_tr', locals:{template_deck_card:template_deck_card} %>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/admin/template_decks/_template_deck_tr.html.erb
<tr class="card-info">
  <td class="card-name col-md-3">
    <%= link_to template_deck_card.card.name, '#', title:('<img src="' + card_image(template_deck_card.card) + '" />') , data:{toggle:'tooltip', html:true}, class:'card-image-link' %>
  </td>
  <td class="col-md-1">
    <%= template_deck_card.quantity %>
  </td>
  <td class="card-type col-md-3">
    <%= template_deck_card.card.card_type %>
  </td>
  <td class="col-md-1">
    <%= template_deck_card.card.rarity %>
  </td>
  <td class="col-md-1">
    <%= "$#{template_deck_card.card.get_price}" %>
  </td>
  <td class="col-md-2 td-links">
    <%= link_to '<span class="fa fa-cog"></span> edit'.html_safe, edit_admin_template_deck_template_deck_card_path(@template_deck, template_deck_card), remote:true %>
    <%= link_to "<span class='fa fa-times-circle'></span> remove".html_safe, admin_template_deck_template_deck_card_path(@template_deck, template_deck_card), method: :delete, remote:true, class:'text-danger text-bold' %>
  </td>
</tr>

app/views/admin/template_decks/index.html.erb
<%= link_to "<span class='fa fa-plus-circle'></span> create template deck".html_safe, new_admin_template_deck_path, remote:true, class:'btn btn-outline btn-default btn-wd pull-right' %>

<h1>Template Decks</h1>

<% if @template_decks.blank? %>
  <p>You do not have any template decks created. Click "create template deck" above to begin a new one.</p>
<% else %>
<div class="card-list-table">
  <table class="table card-list-table">
    <thead>
        <td>Name</td>
        <td>Description</td>
    </thead>
    <tbody>
    <% @template_decks.each do |template_deck| %>
      <tr class="template_deck-<%= template_deck.id %>">
        <td><%= link_to template_deck.name, admin_template_deck_path(template_deck) %></td>
        <td><%= simple_format template_deck.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <div class="panel-body">
		<%= will_paginate @template_decks, :class => 'simple_pager pull-right', :previous_label => '&laquo; previous', :next_label => 'next &raquo;' %>
  </div>
</div>
<% end %>

app/views/admin/template_decks/launch_form.js.erb
$("#form-target").html("<%= escape_javascript(render 'admin/template_decks/modal_form') %>");
$('#modal-form').modal('show');

app/views/admin/template_decks/show.html.erb
<div class="row">
  <div class="col-md-12">

      <div class="card-list-table">
        <div class="card-list-heading align-left">
          <div class="pull-right">
            <%= link_to "<span class='fa fa-cog'></span> edit".html_safe, edit_admin_template_deck_path(@template_deck), class:'btn btn-large btn-primary', remote:true %>
            <%= link_to "<span class='fa fa-times-circle'></span> delete".html_safe, admin_template_deck_path(@template_deck), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-large btn-danger' %>
          </div>
          <h1>
            <%= @template_deck.name %>
          </h1>
          <% if @template_deck.description.present? %>
          <div class="row description-row">
            <div class="col-md-9">
              <h3>Description</h3>
              <%= simple_format @template_deck.description %>
            </div>
          </div>
          <% end %>
        </div>

        <%= render partial:'admin/template_decks/template_deck_table', locals:{ template_deck_card_hash:@template_deck_card_hash } %>

        <%= render partial: 'admin/template_decks/sideboard_table', locals:{sideboard_template_deck_cards:@template_deck.template_deck_cards.sideboard} %>
    </div>

  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <h3>Add new card</h3>
    <% @template_deck_card = @template_deck.template_deck_cards.build %>
    <%= render partial: 'admin/template_deck_cards/form' %>
  </div>
</div>
<br>

<script>

    $('.template-deck-card-cancel a.btn').click(function(e) {
        $('#card_name, #template_deck_card_quantity').val('');
        $('#template_deck_card_sideboard').prop( "checked", false );
        e.preventDefault();
    });

    $('#card_name').autocomplete({
        source: $('#card_name').data('autocomplete-source'),
        dataType: "json",
        minLength: 2,
        focus: function(event, ui) {
            event.preventDefault();
            $('#card_name').val(ui.item.label);
            $('#template_deck_card_card_id').val(ui.item.value);
        },
        select: function(event, ui) {
            event.preventDefault();
            $('#card_name').val(ui.item.label);
            $('#template_deck_card_card_id').val(ui.item.value);
        },
        _renderItem: function( ul, item ) {
            return $( "<li>" )
                    .attr( "data-value", item.value )
                    .append("<img src='" + item.card_image_url + "' />")
                    .appendTo( ul );
        }
    });

    $.ui.autocomplete.prototype._renderItem = function(ul, item) {
        return $("<li></li>")
                .data("item.autocomplete", item)
                .append(
                '<a href="' + item.search_cards_url + '"><div class="ui-card-price pull-right badge badge-success">' + item.card_price + '</div>'
                +  '<img src="' + item.card_image_url + '" class="pull-left ui-card-image" />'
                +  '<div class="ui-card-title">' + item.label + '</div>'
                +  '<div class="ui-card-type">' + item.card_color_and_type + ' | ' + item.card_rarity + '</div>'
                +  '<div class="ui-card-description">' + item.card_text + '</div>'
                + '<div class="clear"></div></a>'
        )
                .appendTo( ul );
    };
</script>